package soccervs.persistence.eventos.core.entities.enums;

public enum EEvento {
		//PASSES
		PASSE_CURTO_RASTEIRO, PASSE_LONGO_RASTEIRO, PASSE_MEDIO_RASTEIRO,
		PASSE_CURTO_MEDIO, PASSE_LONGO_MEDIO, PASSE_MEDIO_MEDIO,
		PASSE_CURTO_ALTO, PASSE_LONGO_ALTO, PASSE_MEDIO_ALTO,
		
		//CRUZAMENTOS
		CRUZAMENTO_CURTO_RASTEIRO, CRUZAMENTO_LONGO_RASTEIRO, CRUZAMENTO_MEDIO_RASTEIRO,
		CRUZAMENTO_CURTO_MEDIO, CRUZAMENTO_LONGO_MEDIO, CRUZAMENTO_MEDIO_MEDIO,
		CRUZAMENTO_CURTO_ALTO, CRUZAMENTO_LONGO_ALTO, CRUZAMENTO_MEDIO_ALTO,
		
		//DRIBLES
		DRIBLE_CURTO, DRIBLE_MEDIO, DRIBLE_LONGO,
		
		//FALTAS
		FALTA_LEVE, FALTA_MEDIA, FALTA_PESADA,
		
		//COBERTURA
		COBERTURA_SIMPLES, COBERTURA_DUPLA, COBERTURA_TRIPLA,
		
		//FINALIZACOES
		FINALIZACAO_CURTO_RASTEIRO, FINALIZACAO_LONGO_RASTEIRO, FINALIZACAO_MEDIO_RASTEIRO,
		FINALIZACAO_CURTO_MEDIO, FINALIZACAO_LONGO_MEDIO, FINALIZACAO_MEDIO_MEDIO,
		FINALIZACAO_CURTO_ALTO, FINALIZACAO_LONGO_ALTO,FINALIZACAO_MEDIO_ALTO,
}
