server:
  port: ${SERVER_PORT:61004}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:55000/soccervs_persistence
    username: soccervs
    password: soccervs

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      persistence-success: persistence-success
      notify-ending: notify-ending
    consumer:
      group-id: persistence-group
      auto-offset-reset: latest